### ISSUE TITLE
random() arduino function is random(lo,hi), with hi being exclusive

### ISSUE THREAD

**Issue by jaanmcleod** [mfhughes128/cw-trainer#3]
Hi :  the random(lo, hi) function is inclusive lo and exclusive hi, so that for instance, Z will never appear if one makes the call random(10,35). It needs to be called as random(lo, hi+1).

John Mcleod  N6RCD

**Comment by mfhughes128** [comment]
Ahh... Thanks! I'll put in a hot fix for that.

Mike Hughes KC1MR
